using System.Text;
using System.Text.Json;
using GFC.BlazorServer.Data;
using GFC.BlazorServer.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace GFC.BlazorServer.Services.Migration;

public class MigrationReportService : IMigrationReportService
{
    private readonly IDbContextFactory<GfcDbContext> _dbFactory;

    public MigrationReportService(IDbContextFactory<GfcDbContext> dbFactory)
    {
        _dbFactory = dbFactory;
    }

    public async Task<string> GenerateReportAsync(int profileId)
    {
        using var db = await _dbFactory.CreateDbContextAsync();
        var profile = await db.MigrationProfiles.FindAsync(profileId);
        if (profile == null) throw new InvalidOperationException("Profile not found");

        var settings = await db.SystemSettings.FirstOrDefaultAsync() ?? new SystemSettings();
        
        var sb = new StringBuilder();
        var now = DateTime.UtcNow;

        // HEADER
        sb.AppendLine("===================================================================");
        sb.AppendLine("          GFC SYSTEM DEPLOYMENT VERIFICATION REPORT               ");
        sb.AppendLine("===================================================================");
        sb.AppendLine();
        sb.AppendLine($"Report ID:       {Guid.NewGuid().ToString().Substring(0, 8).ToUpper()}");
        sb.AppendLine($"Profile Name:    {profile.Name}");
        sb.AppendLine($"Generated At:    {now:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"Generated By:    System Automation (via Admin)");
        sb.AppendLine($"Status:          DEPLOYED TO PRODUCTION");
        sb.AppendLine();

        // ENVIRONMENT SNAPSHOT
        sb.AppendLine("-------------------------------------------------------------------");
        sb.AppendLine("ENVIRONMENT SNAPSHOT");
        sb.AppendLine("-------------------------------------------------------------------");
        sb.AppendLine($"Hosting Env:     {settings.HostingEnvironment}");
        sb.AppendLine($"Primary Domain:  {settings.PrimaryDomain ?? "Not Configured"}");
        sb.AppendLine($"Access Mode:     {settings.AccessMode}");
        sb.AppendLine($"VPN Enforced:    {(settings.EnforceVpn ? "YES" : "NO")}");
        sb.AppendLine($"VPN Subnet:      {settings.WireGuardSubnet}");
        sb.AppendLine($"Backup Active:   {(string.IsNullOrEmpty(settings.BackupMethod) ? "NO" : "YES")}");
        sb.AppendLine($"Safe Mode:       {(settings.SafeModeEnabled ? "ENABLED" : "DISABLED")}");
        sb.AppendLine();

        // GATE VERIFICATION RESULTS
        sb.AppendLine("-------------------------------------------------------------------");
        sb.AppendLine("VERIFICATION GATES");
        sb.AppendLine("-------------------------------------------------------------------");
        
        var gates = JsonSerializer.Deserialize<Dictionary<string, GateStatus>>(profile.GatesStatusJson ?? "{}") 
                    ?? new Dictionary<string, GateStatus>();

        int idx = 1;
        foreach (var key in new[] { "VPN", "Router", "Backup", "Restore", "SafeMode" }) // Order matters
        {
            if (gates.TryGetValue(key, out var gate))
            {
                string status = gate.Passed ? "PASS" : "FAIL";
                string method = gate.IsAutomated ? "Automated" : "Manual Attestation";
                sb.AppendLine($"{idx}. {key,-12} [{status}]  Mode: {method}");
                sb.AppendLine($"   Verified: {gate.LastCheckedUtc?.ToString("yyyy-MM-dd HH:mm:ss") ?? "N/A"} UTC");
                if (!string.IsNullOrEmpty(gate.Message))
                {
                    sb.AppendLine($"   Note:     {gate.Message}");
                }
                sb.AppendLine();
            }
            idx++;
        }

        // DECLARATION
        sb.AppendLine("-------------------------------------------------------------------");
        sb.AppendLine("DECLARATION");
        sb.AppendLine("-------------------------------------------------------------------");
        sb.AppendLine("This system configuration has been verified against the defined");
        sb.AppendLine("security and reliability gates. The environment is declared");
        sb.AppendLine("SECURE and READY for live production traffic.");
        sb.AppendLine();
        sb.AppendLine("===================================================================");
        sb.AppendLine("END OF REPORT");

        string reportText = sb.ToString();

        // Save to DB
        profile.ReportContentTxt = reportText;
        profile.ReportGeneratedAtUtc = now;
        await db.SaveChangesAsync();

        return reportText;
    }

    public async Task<string?> GetFormattedReportAsync(int profileId)
    {
        using var db = await _dbFactory.CreateDbContextAsync();
        var profile = await db.MigrationProfiles.FindAsync(profileId);
        return profile?.ReportContentTxt;
    }
}
