import type { AnimationConfig } from "./types";

// Import all 20 Button effect components
import { LiquidRippleButton } from "@/components/animations/buttons/LiquidRippleButton";
import { GlassMorphSlideButton } from "@/components/animations/buttons/GlassMorphSlideButton";
import { NeonPulseEdgeGlowButton } from "@/components/animations/buttons/NeonPulseEdgeGlowButton";
import { MagneticAttractionButton } from "@/components/animations/buttons/MagneticAttractionButton";
import { SoftBodyGooeyButton } from "@/components/animations/buttons/SoftBodyGooeyButton";
import { ShockwaveClickButton } from "@/components/animations/buttons/ShockwaveClickButton";
import { ShimmerSweepButton } from "@/components/animations/buttons/ShimmerSweepButton";
import { Tilt3DParallaxButton } from "@/components/animations/buttons/Tilt3DParallaxButton";
import { ColorBloomButton } from "@/components/animations/buttons/ColorBloomButton";
import { ParticleBurstButton } from "@/components/animations/buttons/ParticleBurstButton";
import { LaserBeamBorderTraceButton } from "@/components/animations/buttons/LaserBeamBorderTraceButton";
import { AuroraGradientButton } from "@/components/animations/buttons/AuroraGradientButton";
import { MorphingShapeButton } from "@/components/animations/buttons/MorphingShapeButton";
import { DynamicShadowButton } from "@/components/animations/buttons/DynamicShadowButton";
import { InnerRippleGlowButton } from "@/components/animations/buttons/InnerRippleGlowButton";
import { FireflySparkleButton } from "@/components/animations/buttons/FireflySparkleButton";
import { SplitRevealButton } from "@/components/animations/buttons/SplitRevealButton";
import { PopOut3DLayeredButton } from "@/components/animations/buttons/PopOut3DLayeredButton";
import { AuraPressureButton } from "@/components/animations/buttons/AuraPressureButton";
import { HolographicGlitchButton } from "@/components/animations/buttons/HolographicGlitchButton";

// Import Icon Story Button components
import {
  EnvelopeToPaperPlaneButton,
  EnvelopeFlapBurstButton,
  PaperPlaneRunwayButton,
  InboxZeroSweepButton,
  ChatBubbleRocketButton,
  TypingDotsBlastButton,
  FolderArrowLaunchButton,
  CloudUploadReverseButton,
  HeartConfettiPopButton,
  StarSupernovaButton,
  MusicEqualizerButton,
  CartCheckoutArrowButton,
  MagicWandSparkleButton,
  PortalMorphButton,
  TrashVacuumButton,
  LockUnlockSlideButton,
  CameraPhotoPopButton,
  EnvelopeMultiMorphButton,
  FlipIconCardButton,
  ParticleTransformButton,
} from "@/components/animations/buttons/IconStoryButtons";

export const BUTTONS_CATEGORY_ID = "Buttons";

// Placeholder code for Button animations
const defaultButtonCode = `"use client";

import React from "react";
import { motion } from "framer-motion";

// Button animation component code here`;

export const buttonAnimations: AnimationConfig[] = [
  {
    id: "button-liquid-ripple",
    name: "Liquid Ripple",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: LiquidRippleButton,
    code: defaultButtonCode,
  },
  {
    id: "button-glass-morph-slide",
    name: "Glass Morph Slide",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GlassMorphSlideButton,
    code: defaultButtonCode,
  },
  {
    id: "button-neon-pulse-glow",
    name: "Neon Pulse Edge Glow",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: NeonPulseEdgeGlowButton,
    code: defaultButtonCode,
  },
  {
    id: "button-magnetic-attraction",
    name: "Magnetic Attraction",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: MagneticAttractionButton,
    code: defaultButtonCode,
  },
  {
    id: "button-soft-body-gooey",
    name: "Soft-Body Gooey",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: SoftBodyGooeyButton,
    code: defaultButtonCode,
  },
  {
    id: "button-shockwave-click",
    name: "Shockwave Click",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: ShockwaveClickButton,
    code: defaultButtonCode,
  },
  {
    id: "button-shimmer-sweep",
    name: "Shimmer Sweep",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: ShimmerSweepButton,
    code: defaultButtonCode,
  },
  {
    id: "button-3d-tilt-parallax",
    name: "3D Tilt Parallax",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: Tilt3DParallaxButton,
    code: defaultButtonCode,
  },
  {
    id: "button-color-bloom",
    name: "Color Bloom",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: ColorBloomButton,
    code: defaultButtonCode,
  },
  {
    id: "button-particle-burst",
    name: "Particle Burst",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: ParticleBurstButton,
    code: defaultButtonCode,
  },
  {
    id: "button-laser-border-trace",
    name: "Laser Beam Border Trace",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: LaserBeamBorderTraceButton,
    code: defaultButtonCode,
  },
  {
    id: "button-aurora-gradient",
    name: "Aurora Gradient",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: AuroraGradientButton,
    code: defaultButtonCode,
  },
  {
    id: "button-morphing-shape",
    name: "Morphing Shape",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: MorphingShapeButton,
    code: defaultButtonCode,
  },
  {
    id: "button-dynamic-shadow",
    name: "Dynamic Shadow",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: DynamicShadowButton,
    code: defaultButtonCode,
  },
  {
    id: "button-inner-ripple-glow",
    name: "Ripple Inside Glow",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: InnerRippleGlowButton,
    code: defaultButtonCode,
  },
  {
    id: "button-firefly-sparkle",
    name: "Firefly Sparkle",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: FireflySparkleButton,
    code: defaultButtonCode,
  },
  {
    id: "button-split-reveal",
    name: "Split Reveal",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: SplitRevealButton,
    code: defaultButtonCode,
  },
  {
    id: "button-3d-pop-out-layers",
    name: "3D Pop-Out Layered",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: PopOut3DLayeredButton,
    code: defaultButtonCode,
  },
  {
    id: "button-aura-pressure",
    name: "Aura Pressure",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: AuraPressureButton,
    code: defaultButtonCode,
  },
  {
    id: "button-holographic-glitch",
    name: "Holographic Glitch",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: HolographicGlitchButton,
    code: defaultButtonCode,
  },
  // Icon Story Buttons (20 total)
  {
    id: "button-icon-envelope-plane",
    name: "Envelope to Paper Plane",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: EnvelopeToPaperPlaneButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-envelope-flap-burst",
    name: "Envelope Flap Burst",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: EnvelopeFlapBurstButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-plane-runway",
    name: "Paper Plane Runway",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: PaperPlaneRunwayButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-inbox-zero-sweep",
    name: "Inbox Zero Sweep",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: InboxZeroSweepButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-chat-rocket",
    name: "Chat Bubble Rocket",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: ChatBubbleRocketButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-typing-blast",
    name: "Typing Dots Blast",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: TypingDotsBlastButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-folder-arrow",
    name: "Folder Arrow Launch",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: FolderArrowLaunchButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-cloud-reverse",
    name: "Cloud Upload Reverse",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CloudUploadReverseButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-heart-confetti",
    name: "Heart Confetti Pop",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: HeartConfettiPopButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-star-supernova",
    name: "Star Supernova",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: StarSupernovaButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-music-equalizer",
    name: "Music Equalizer",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: MusicEqualizerButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-cart-checkout",
    name: "Cart Checkout Arrow",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CartCheckoutArrowButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-wand-sparkle",
    name: "Magic Wand Sparkle",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: MagicWandSparkleButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-portal-morph",
    name: "Portal Morph",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: PortalMorphButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-trash-vacuum",
    name: "Trash Vacuum",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: TrashVacuumButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-lock-unlock",
    name: "Lock Unlock Slide",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: LockUnlockSlideButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-camera-photo",
    name: "Camera Photo Pop",
    category: BUTTONS_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CameraPhotoPopButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-envelope-sequence",
    name: "Envelope Multi Morph",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: EnvelopeMultiMorphButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-flip-card",
    name: "3D Flip Icon Card",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: FlipIconCardButton,
    code: defaultButtonCode,
  },
  {
    id: "button-icon-particle-transform",
    name: "Particle Transform",
    category: BUTTONS_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: ParticleTransformButton,
    code: defaultButtonCode,
  },
];

