import type { AnimationConfig } from "./types";
import type { GfcWebsiteType } from "./types";
import {
  GfcHeroSimpleFade,
  GfcHeroDiagonalSplit,
  GfcAnnouncementRibbon,
  GfcSectionHeaderGoldUnderline,
} from "@/components/animations/gfc/GfcWebsiteHeroAndBanners";
import {
  GfcCtaRentHallButton,
  GfcCtaJoinButton,
  GfcCtaEmailButton,
  GfcCtaDonateButton,
  GfcCtaLearnMoreButton,
  GfcCtaBookNowButton,
  GfcCtaContactButton,
} from "@/components/animations/gfc/GfcWebsiteCtaButtons";
import {
  GfcCardMembershipStats,
  GfcCardHallFeatureStrip,
  GfcCardFloorplanReveal,
  GfcCardPhotoMosaic,
  GfcCardEventHover,
  GfcCardTeamMember,
} from "@/components/animations/gfc/GfcWebsiteCardsTiles";
import {
  GfcSectionParallaxHero,
  GfcSectionHistoryTimeline,
  GfcSectionRentalSteps,
  GfcSectionWaveDivider,
  GfcSectionStickyMiniNavDemo,
} from "@/components/animations/gfc/GfcWebsiteSections";
import {
  GfcBannerEventCountdown,
  GfcChipOpenRentals,
  GfcFooterCtaBar,
  GfcStripContactInfo,
} from "@/components/animations/gfc/GfcWebsiteBannersStatus";
import {
  GfcBrandDonationImpactMeter,
  GfcBrandCrestHighlight,
  GfcBrandPerfectForBadges,
  GfcBrandTestimonialsSlider,
  GfcBrandMembershipTypeFlipCards,
} from "@/components/animations/gfc/GfcWebsiteBrandingImpact";
import {
  GfcCalendarAvailableTile,
  GfcCalendarBookedTile,
  GfcCalendarPendingTile,
  GfcCalendarHeaderSlide,
  GfcCalendarMonthSwitch,
  GfcCalendarRangeHighlight,
} from "@/components/animations/gfc/GfcWebsiteCalendar";
import {
  GfcCalendarAvailableDayPulse,
  GfcCalendarAvailableHoverLift,
  GfcCalendarSoftAvailabilityRipple,
  GfcCalendarAvailabilityGradientSweep,
  GfcCalendarFaintCheckmarkReveal,
  GfcCalendarMorningEveningColorSplit,
  GfcCalendarPriorityDateGlow,
  GfcCalendarBookedDayLockIn,
  GfcCalendarConflictShakeRed,
  GfcCalendarFullDayFlashWarning,
  GfcCalendarBlockedDateStripe,
  GfcCalendarGapRuleViolationPulse,
  GfcCalendarEventOverlapSlideAlert,
  GfcCalendarHolidaySealStamp,
  GfcCalendarAddEventSlideUpForm,
  GfcCalendarAddEventTargetHighlight,
  GfcCalendarEventCreatedSuccessBurst,
  GfcCalendarEventDeniedShake,
  GfcCalendarEventSavedRibbon,
  GfcCalendarAdminOverrideGlow,
  GfcCalendarAdminEditTileFlip,
  GfcCalendarAdminBulkBlockingSweep,
  GfcCalendarMonthSlideLeft,
  GfcCalendarMonthSlideRight,
  GfcCalendarMonthFadeReveal,
} from "@/components/animations/gfc/GfcWebsiteCalendarExpanded";
import {
  CalendarPageFlip,
  CalendarDatePulse,
  CalendarDayGlow,
  CalendarWeekSlide,
  CalendarPopInEvent,
  CalendarBookedStamp,
  CalendarAvailableFade,
  CalendarDragAddEvent,
  CalendarBounceDayMarker,
  CalendarSwipeMonth,
  CalendarPeelBackReveal,
  CalendarHighlightRange,
  CalendarDotPop,
  CalendarEventRibbon,
  CalendarMonthCarousel,
  CalendarFogUnavailable,
  CalendarFlashAvailable,
  CalendarEventPing,
  CalendarEventDropIn,
  CalendarAvailabilityChecker,
  CalendarTapToAdd,
  CalendarHeatMapGlow,
  CalendarSoftWaveTransition,
  CalendarEventFlagRise,
  CalendarBookedLockIn,
} from "@/components/animations/gfc/GfcCalendarPhaseC2";
import {
  CalendarCreateEventPop,
  CalendarDragToCreateSlot,
  CalendarEventExpandForm,
  CalendarDayPressPopup,
  CalendarSlideInEventCreator,
  CalendarTapAddMarker,
  CalendarEventGrowHighlight,
  CalendarDropEventIntoDay,
  CalendarSelectWindowPulse,
  CalendarEventBubbleRise,
} from "@/components/animations/gfc/GfcCalendarEventCreation";
import AmericanFlagWave from "@/components/animations/gfc/AmericanFlagWave";
import { AmericanFlagWebGL } from "../components/AmericanFlagWebGL";

export const GFC_WEBSITE_CATEGORY_ID = "gfc-website";

// Placeholder code for GFC Website animations
const defaultGfcCode = `"use client";

import React from "react";
import { motion } from "framer-motion";

// GFC Website Animation Component
export default function GfcWebsiteAnimation() {
  return (
    <div className="flex h-full w-full items-center justify-center">
      {/* Animation content */}
    </div>
  );
}
`;

export const gfcWebsiteAnimations: AnimationConfig[] = [
  {
    id: "gfc-hero-simple-fade",
    name: "GFC Hero – Simple Fade",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcHeroSimpleFade,
    code: defaultGfcCode,
    gfcType: "hero-banner",
  },
  {
    id: "gfc-hero-diagonal-split",
    name: "GFC Hero – Diagonal Split",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcHeroDiagonalSplit,
    code: defaultGfcCode,
    gfcType: "hero-banner",
  },
  {
    id: "gfc-announcement-ribbon",
    name: "GFC Announcement Ribbon",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcAnnouncementRibbon,
    code: defaultGfcCode,
    gfcType: "banner-status",
  },
  {
    id: "gfc-section-header-gold-underline",
    name: "GFC Section Header – Gold Underline",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcSectionHeaderGoldUnderline,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  // GFC Website CTA Buttons (7 total)
  {
    id: "gfc-cta-rent-hall",
    name: "GFC CTA – Rent Hall",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaRentHallButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-join",
    name: "GFC CTA – Join the Club",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaJoinButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-email",
    name: "GFC CTA – Email Us",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaEmailButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-donate",
    name: "GFC CTA – Donate",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaDonateButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-learn-more",
    name: "GFC CTA – Learn More",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaLearnMoreButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-book-now",
    name: "GFC CTA – Book Now",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaBookNowButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  {
    id: "gfc-cta-contact",
    name: "GFC CTA – Contact Us",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCtaContactButton,
    code: defaultGfcCode,
    gfcType: "cta-button",
  },
  // GFC Website Cards & Tiles (6 total)
  {
    id: "gfc-card-membership-stats",
    name: "GFC Card – Membership Stats",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCardMembershipStats,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  {
    id: "gfc-card-hall-feature-strip",
    name: "GFC Strip – Hall Features",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "sm",
    component: GfcCardHallFeatureStrip,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  {
    id: "gfc-card-floorplan-reveal",
    name: "GFC Card – Floorplan Reveal",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "sm",
    component: GfcCardFloorplanReveal,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  {
    id: "gfc-card-photo-mosaic",
    name: "GFC Card – Photo Mosaic",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCardPhotoMosaic,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  {
    id: "gfc-card-event-hover",
    name: "GFC Card – Event",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCardEventHover,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  {
    id: "gfc-card-team-member",
    name: "GFC Card – Team Member",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCardTeamMember,
    code: defaultGfcCode,
    gfcType: "card-tile",
  },
  // GFC Website Sections & Layout (5 total)
  {
    id: "gfc-section-parallax-hero",
    name: "GFC Section – Parallax Hero",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcSectionParallaxHero,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  {
    id: "gfc-section-history-timeline",
    name: "GFC Section – History Timeline",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcSectionHistoryTimeline,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  {
    id: "gfc-section-rental-steps",
    name: "GFC Section – Rental Steps",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcSectionRentalSteps,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  {
    id: "gfc-section-wave-divider",
    name: "GFC Divider – Wave",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcSectionWaveDivider,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  {
    id: "gfc-section-sticky-mini-nav",
    name: "GFC Section – Sticky Mini Nav Demo",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcSectionStickyMiniNavDemo,
    code: defaultGfcCode,
    gfcType: "section-layout",
  },
  // GFC Website Banners & Status (4 total)
  {
    id: "gfc-banner-event-countdown",
    name: "GFC Banner – Event Countdown",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcBannerEventCountdown,
    code: defaultGfcCode,
    gfcType: "banner-status",
  },
  {
    id: "gfc-chip-open-rentals",
    name: "GFC Chip – Open for Rentals",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 1,
    previewSize: "sm",
    component: GfcChipOpenRentals,
    code: defaultGfcCode,
    gfcType: "banner-status",
  },
  {
    id: "gfc-footer-cta-bar",
    name: "GFC Footer – CTA Bar",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcFooterCtaBar,
    code: defaultGfcCode,
    gfcType: "banner-status",
  },
  {
    id: "gfc-strip-contact-info",
    name: "GFC Strip – Contact Info",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcStripContactInfo,
    code: defaultGfcCode,
    gfcType: "banner-status",
  },
  // GFC Website Branding & Impact (5 total)
  {
    id: "gfc-brand-donation-impact-meter",
    name: "GFC Brand – Donation Impact Meter",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcBrandDonationImpactMeter,
    code: defaultGfcCode,
    gfcType: "branding-impact",
  },
  {
    id: "gfc-brand-crest-highlight",
    name: "GFC Brand – Crest Highlight",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcBrandCrestHighlight,
    code: defaultGfcCode,
    gfcType: "branding-impact",
  },
  {
    id: "gfc-brand-perfect-for-badges",
    name: "GFC Brand – Perfect For Badges",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcBrandPerfectForBadges,
    code: defaultGfcCode,
    gfcType: "branding-impact",
  },
  {
    id: "gfc-brand-testimonials-slider",
    name: "GFC Brand – Testimonials Slider",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcBrandTestimonialsSlider,
    code: defaultGfcCode,
    gfcType: "branding-impact",
  },
  {
    id: "gfc-brand-membership-type-flip-cards",
    name: "GFC Brand – Membership Type Flip Cards",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcBrandMembershipTypeFlipCards,
    code: defaultGfcCode,
    gfcType: "branding-impact",
  },
  // GFC Website Calendar (6 total)
  {
    id: "gfc-calendar-available-tile",
    name: "GFC Calendar – Available Tile Glow",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarAvailableTile,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-booked-tile",
    name: "GFC Calendar – Booked Tile Lock",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarBookedTile,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-pending-tile",
    name: "GFC Calendar – Pending Tile Pulse",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarPendingTile,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-header-slide",
    name: "GFC Calendar – Header Slide",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarHeaderSlide,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-month-switch",
    name: "GFC Calendar – Month Switch",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcCalendarMonthSwitch,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-range-highlight",
    name: "GFC Calendar – Range Highlight",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcCalendarRangeHighlight,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // GFC Website Calendar Expanded (25 total) - Phase C1
  // Availability Indicators (7)
  {
    id: "gfc-calendar-available-day-pulse",
    name: "GFC Calendar – Available Day Pulse",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarAvailableDayPulse,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-available-hover-lift",
    name: "GFC Calendar – Available Hover Lift",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarAvailableHoverLift,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-soft-availability-ripple",
    name: "GFC Calendar – Soft Availability Ripple",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarSoftAvailabilityRipple,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-availability-gradient-sweep",
    name: "GFC Calendar – Availability Gradient Sweep",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarAvailabilityGradientSweep,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-faint-checkmark-reveal",
    name: "GFC Calendar – Faint Checkmark Reveal",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarFaintCheckmarkReveal,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-morning-evening-color-split",
    name: "GFC Calendar – Morning Evening Color Split",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarMorningEveningColorSplit,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-priority-date-glow",
    name: "GFC Calendar – Priority Date Glow",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarPriorityDateGlow,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Booked / Conflict States (7)
  {
    id: "gfc-calendar-booked-day-lock-in",
    name: "GFC Calendar – Booked Day Lock In",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarBookedDayLockIn,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-conflict-shake-red",
    name: "GFC Calendar – Conflict Shake Red",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarConflictShakeRed,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-full-day-flash-warning",
    name: "GFC Calendar – Full Day Flash Warning",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarFullDayFlashWarning,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-blocked-date-stripe",
    name: "GFC Calendar – Blocked Date Stripe",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarBlockedDateStripe,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-gap-rule-violation-pulse",
    name: "GFC Calendar – Gap Rule Violation Pulse",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarGapRuleViolationPulse,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-event-overlap-slide-alert",
    name: "GFC Calendar – Event Overlap Slide Alert",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "sm",
    component: GfcCalendarEventOverlapSlideAlert,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-holiday-seal-stamp",
    name: "GFC Calendar – Holiday Seal Stamp",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarHolidaySealStamp,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Event Creation Flow (5)
  {
    id: "gfc-calendar-add-event-slide-up-form",
    name: "GFC Calendar – Add Event Slide Up Form",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: GfcCalendarAddEventSlideUpForm,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-add-event-target-highlight",
    name: "GFC Calendar – Add Event Target Highlight",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarAddEventTargetHighlight,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-event-created-success-burst",
    name: "GFC Calendar – Event Created Success Burst",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarEventCreatedSuccessBurst,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-event-denied-shake",
    name: "GFC Calendar – Event Denied Shake",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarEventDeniedShake,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-event-saved-ribbon",
    name: "GFC Calendar – Event Saved Ribbon",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarEventSavedRibbon,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Admin-Only Visuals (3)
  {
    id: "gfc-calendar-admin-override-glow",
    name: "GFC Calendar – Admin Override Glow",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "sm",
    component: GfcCalendarAdminOverrideGlow,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-admin-edit-tile-flip",
    name: "GFC Calendar – Admin Edit Tile Flip",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "sm",
    component: GfcCalendarAdminEditTileFlip,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-admin-bulk-blocking-sweep",
    name: "GFC Calendar – Admin Bulk Blocking Sweep",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "sm",
    component: GfcCalendarAdminBulkBlockingSweep,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Month Navigation & Transitions (3)
  {
    id: "gfc-calendar-month-slide-left",
    name: "GFC Calendar – Month Slide Left",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarMonthSlideLeft,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-month-slide-right",
    name: "GFC Calendar – Month Slide Right",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarMonthSlideRight,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "gfc-calendar-month-fade-reveal",
    name: "GFC Calendar – Month Fade Reveal",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: GfcCalendarMonthFadeReveal,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Phase C2 - 25 New Calendar Animations
  {
    id: "calendar-page-flip",
    name: "Calendar Page Flip",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarPageFlip,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-date-pulse",
    name: "Calendar Date Pulse",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarDatePulse,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-day-glow",
    name: "Calendar Day Glow",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarDayGlow,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-week-slide",
    name: "Calendar Week Slide",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarWeekSlide,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-pop-in-event",
    name: "Calendar Pop In Event",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarPopInEvent,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-booked-stamp",
    name: "Calendar Booked Stamp",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarBookedStamp,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-available-fade",
    name: "Calendar Available Fade",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarAvailableFade,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-drag-add-event",
    name: "Calendar Drag Add Event",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarDragAddEvent,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-bounce-day-marker",
    name: "Calendar Bounce Day Marker",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarBounceDayMarker,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-swipe-month",
    name: "Calendar Swipe Month",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarSwipeMonth,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-peel-back-reveal",
    name: "Calendar Peel Back Reveal",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarPeelBackReveal,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-highlight-range",
    name: "Calendar Highlight Range",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarHighlightRange,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-dot-pop",
    name: "Calendar Dot Pop",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarDotPop,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-event-ribbon",
    name: "Calendar Event Ribbon",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventRibbon,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-month-carousel",
    name: "Calendar Month Carousel",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarMonthCarousel,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-fog-unavailable",
    name: "Calendar Fog Unavailable",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarFogUnavailable,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-flash-available",
    name: "Calendar Flash Available",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarFlashAvailable,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-event-ping",
    name: "Calendar Event Ping",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventPing,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-event-drop-in",
    name: "Calendar Event Drop In",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventDropIn,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-availability-checker",
    name: "Calendar Availability Checker",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarAvailabilityChecker,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-tap-to-add",
    name: "Calendar Tap To Add",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarTapToAdd,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-heat-map-glow",
    name: "Calendar Heat Map Glow",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarHeatMapGlow,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-soft-wave-transition",
    name: "Calendar Soft Wave Transition",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarSoftWaveTransition,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-event-flag-rise",
    name: "Calendar Event Flag Rise",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventFlagRise,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  {
    id: "calendar-booked-lock-in",
    name: "Calendar Booked Lock In",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarBookedLockIn,
    code: defaultGfcCode,
    gfcType: "calendar",
  },
  // Phase C3 - 10 Event Creation Animations
  {
    id: "calendar-create-event-pop",
    name: "Calendar Create Event Pop",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarCreateEventPop,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-drag-to-create-slot",
    name: "Calendar Drag To Create Slot",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarDragToCreateSlot,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-event-expand-form",
    name: "Calendar Event Expand Form",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarEventExpandForm,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-day-press-popup",
    name: "Calendar Day Press Popup",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarDayPressPopup,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-slide-in-event-creator",
    name: "Calendar Slide In Event Creator",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarSlideInEventCreator,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-tap-add-marker",
    name: "Calendar Tap Add Marker",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarTapAddMarker,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-event-grow-highlight",
    name: "Calendar Event Grow Highlight",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventGrowHighlight,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-drop-event-into-day",
    name: "Calendar Drop Event Into Day",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 3,
    previewSize: "md",
    component: CalendarDropEventIntoDay,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-select-window-pulse",
    name: "Calendar Select Window Pulse",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarSelectWindowPulse,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  {
    id: "calendar-event-bubble-rise",
    name: "Calendar Event Bubble Rise",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "md",
    component: CalendarEventBubbleRise,
    code: defaultGfcCode,
    gfcType: "calendar-event-creation",
  },
  // Flags & Patriotic
  {
    id: "gfc-american-flag-wave",
    name: "American Flag – Photographic Wave",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "lg",
    component: AmericanFlagWave,
    code: defaultGfcCode,
    gfcType: "flags-patriotic",
  },
  {
    id: "gfc-american-flag-webgl",
    name: "American Flag – WebGL Wave",
    category: GFC_WEBSITE_CATEGORY_ID,
    complexity: 2,
    previewSize: "lg",
    component: AmericanFlagWebGL,
    code: defaultGfcCode,
    gfcType: "flags-patriotic",
  },
];

