import type { ComponentType } from "react";
import { animationRegistry as coreRegistry } from "./core/AnimationRegistry";
import type { GfcWebsiteType } from "./core/types";

// Central Animation Metadata Registry
// This registry provides navigation and metadata for all animations

export type AnimationMeta = {
  id: string;
  name: string;
  description: string;
  category?: "basic" | "intermediate" | "advanced" | string;
  difficulty?: number; // 1-3 scale
  usageCategory?: "hero" | "section-transition" | "card-tile" | "button-cta" | "buttons" | "text-headline" | "text-fx" | "background-ambient" | "interactive" | "forms-auth" | "dashboards-metrics" | "media-galleries" | "gfc-website" | "flags" | string;
  route?: string; // Custom route if different from default
  component?: ComponentType<any>;
  gfcType?: GfcWebsiteType;
  addedAt?: string; // ISO date string "YYYY-MM-DD" when this preset was introduced
};

// Map core registry to metadata format
export const animations: AnimationMeta[] = [
  {
    id: "pulseCircle",
    name: "Pulse Circle",
    description: "A simple pulsing circle animation with smooth scale transitions.",
    category: "basic",
    difficulty: 1,
    usageCategory: "button-cta",
    route: "/playground",
  },
  {
    id: "slidingSquare",
    name: "Sliding Square",
    description: "A square that slides horizontally back and forth.",
    category: "basic",
    difficulty: 1,
    usageCategory: "section-transition",
    route: "/playground",
  },
  {
    id: "floatingText",
    name: "Floating Text",
    description: "Text that floats up and down with opacity changes.",
    category: "basic",
    difficulty: 2,
    usageCategory: "text-headline",
    route: "/playground",
  },
  {
    id: "morphingShapeFlow",
    name: "Morphing Shape Flow",
    description: "Advanced morphing animation that transitions between multiple SVG shapes with gradient colors.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "hologramGridWarp",
    name: "Hologram Grid Warp",
    description: "Interactive neon grid that reacts to mouse movement with perspective skew and z-depth motion effects.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "interactive",
    route: "/playground",
  },
  {
    id: "particleSwarmRibbon",
    name: "Particle Swarm Ribbon",
    description: "Hundreds of particles following a noise field to form a flowing ribbon path with smooth camera drift.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "fractalPulseTunnel",
    name: "Fractal Pulse Tunnel",
    description: "Recursive rings creating a tunnel effect with depth zoom, synchronized pulsing, and dynamic hue shifting.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "quantumPulseGrid",
    name: "Quantum Pulse Grid",
    description: "A pulsating multi-layer grid with quantum-style energy waves and synchronized pulse propagation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "liquidNeonFlux",
    name: "Liquid Neon Flux",
    description: "A flowing neon liquid simulation with morphing energy shapes and dynamic gradient colors.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "hypercubeWarpTunnel",
    name: "Hypercube Warp Tunnel",
    description: "A rotating 4D hypercube warping through space with perspective projection and depth layers.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "liquidMetalMorph",
    name: "Liquid Metal Morph",
    description: "A fluid, metallic morphing animation that smoothly transitions between I, heart, and U shapes with reflective gradients.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "hero",
    route: "/playground",
  },
  {
    id: "singleLinePathMorph",
    name: "Single-Line Path Morph",
    description: "A mesmerizing single continuous stroke that morphs through I, heart, and U shapes without lifting the pen, with a glowing neon trail.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-headline",
    route: "/playground",
  },
  {
    id: "particleCloudMorph",
    name: "Particle Cloud Morph",
    description: "Hundreds of particles that swarm together to form I, heart, and U shapes in sequence, creating a dynamic, living animation effect.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "background-ambient",
    route: "/playground",
  },
  {
    id: "origamiFoldMorph",
    name: "Origami Fold Morph",
    description: "An origami-inspired animation where paper-like shapes fold and unfold to transform between I, heart, and U with 3D perspective effects.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "interactive",
    route: "/playground",
  },
  {
    id: "fireIceDualMorph",
    name: "Fire & Ice Dual Morph",
    description: "A dramatic dual-element animation featuring fire (red/orange) and ice (blue/cyan) that form I and U, then merge into a heart.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "hero",
    route: "/playground",
  },
  {
    id: "compressionMorph",
    name: "Compression Morph",
    description: "Two horizontal bars squeeze 'I LOVE YOU' into 'I ❤️ U' and then into a heart symbol, simulating physical compression.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-headline",
    route: "/playground",
  },
  // Text FX animations
  {
    id: "neon-pulse-glow",
    name: "Neon Pulse Glow",
    description: "Text with outer glow, per-letter sequential fade-in, looping soft pulse and subtle flicker.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "digital-flip-clock",
    name: "Digital Flip Clock",
    description: "Characters appear via vertical flip-card motion like an old digital clock, staggered per character.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "typewriter-ink-bleed",
    name: "Typewriter Ink Bleed",
    description: "Typewriter typing effect with a slight ink-bleed/ripple expansion on each letter as it appears.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "liquid-wave-text",
    name: "Liquid Wave",
    description: "Text emerges from a liquid-like wave distortion with small vertical sinusoidal motion rippling across letters.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "particle-burst-reveal",
    name: "Particle Burst",
    description: "Each character starts as tiny scattered dots that converge into the proper letter.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "floating-balloon-letters",
    name: "Balloon Float",
    description: "Each letter gently floats upward and bobs, with soft scale-in from below.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "metallic-shine-sweep",
    name: "Metallic Shine",
    description: "A diagonal shine passes across the text in a loop, simulating a metallic reflection.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "explode-reform",
    name: "Explode & Reform",
    description: "Text starts intact, explodes outward into pieces, then reassembles into the original text.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "flame-text-morph",
    name: "Flame Flicker",
    description: "Letters flicker vertically/opacity like fire, with warm colors and subtle vertical noise/scale wiggle.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "laser-beam-writing",
    name: "Laser Write",
    description: "A horizontal laser bar sweeps from left to right; letters appear as the beam passes, with spark-like flashes.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "glitch-scramble-decode",
    name: "Glitch Decode",
    description: "Characters rapidly scramble through random letters/symbols before locking into the target text with RGB offset jitter.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "origami-fold-text",
    name: "Origami Fold",
    description: "Each letter folds open from a flat line via 3D rotation on X/Y axis with perspective-like transform.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "rotation-carousel-3d",
    name: "3D Carousel Text",
    description: "Whole text rotates in 3D around Y axis like on a cylinder, briefly hiding and revealing the message.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "ice-freeze-crack",
    name: "Ice Crack Reveal",
    description: "Text appears frosted with cool colors and blur, then a cracking animation reveals sharp clear text.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "bubble-pop-reveal",
    name: "Bubble Pop",
    description: "Small bubbles float up; when they pop, a letter appears in their place.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "warp-speed-stretch",
    name: "Warp Speed",
    description: "Text streaks from the center as stretched lines, then decelerates into clear letters with motion blur effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "ribbon-text-unfold",
    name: "Ribbon Unfold",
    description: "A horizontal ribbon sweeps across; as it moves, letters are unwrapped from the ribbon via masked reveal.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "chromatic-rgb-split",
    name: "Chromatic Split",
    description: "Slight continuous RGB split offset on the text; intensifies on loop moments and then snaps back.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "electric-arc-stitching",
    name: "Electric Stitch",
    description: "Electric arcs travel along an imagined baseline, and as they pass a letter position, that letter appears.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "ink-calligraphy-stroke",
    name: "Calligraphy Stroke",
    description: "A moving stroke reveals each letter as if hand-written via masked text and moving gradient/clipRect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "text-fx",
    route: "/playground",
  },
  // Button animations (20 total)
  {
    id: "button-liquid-ripple",
    name: "Liquid Ripple",
    description: "On click, generates a circular ripple starting at the click position, expanding outward and fading.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-glass-morph-slide",
    name: "Glass Morph Slide",
    description: "Subtle glassmorphism style that slides forward on hover with increased glow and blur effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-neon-pulse-glow",
    name: "Neon Pulse Edge Glow",
    description: "Crisp neon border with continuous pulse glow on hover and explosion effect on click.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-magnetic-attraction",
    name: "Magnetic Attraction",
    description: "Button subtly moves toward cursor position while cursor is near, with snap-back on click.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-soft-body-gooey",
    name: "Soft-Body Gooey",
    description: "Button stretches toward cursor on hover and squishes with rebound on click for a soft-body effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-shockwave-click",
    name: "Shockwave Click",
    description: "On click, emits a circular outline shockwave from center that expands and fades.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-shimmer-sweep",
    name: "Shimmer Sweep",
    description: "On hover, a diagonal shimmer light streak passes across the button surface.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-3d-tilt-parallax",
    name: "3D Tilt Parallax",
    description: "Button tilts in 3D depending on cursor position with smooth parallax effect.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-color-bloom",
    name: "Color Bloom",
    description: "On hover, a blooming color radiates out from cursor position, filling the button background.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-particle-burst",
    name: "Particle Burst",
    description: "On click, emits 30-60 small particles that fly outward and fade in all directions.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-laser-border-trace",
    name: "Laser Beam Border Trace",
    description: "On hover, a laser line travels around the border in sequence (top → right → bottom → left).",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-aurora-gradient",
    name: "Aurora Gradient",
    description: "Background features slow-moving aurora-like gradient waves, intensifying on hover.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-morphing-shape",
    name: "Morphing Shape",
    description: "Smoothly morphs between rounded rectangle, fully pill, and slightly squashed pill shapes on hover.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-dynamic-shadow",
    name: "Dynamic Shadow",
    description: "Shadow direction and length adjust based on cursor position, with press-in effect on click.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-inner-ripple-glow",
    name: "Ripple Inside Glow",
    description: "Constant soft glow border with multiple inward concentric ripples on click, moving inward.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-firefly-sparkle",
    name: "Firefly Sparkle",
    description: "Small glowing fireflies wander slowly around the button, brightening and speeding up on hover.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-split-reveal",
    name: "Split Reveal",
    description: "On hover, button splits into left and right halves revealing a glowing inner core between them.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-3d-pop-out-layers",
    name: "3D Pop-Out Layered",
    description: "Multiple layers separate in z-space on hover, creating a 3D stack effect with compression on click.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-aura-pressure",
    name: "Aura Pressure",
    description: "Subtle outer aura glow that grows on hover and compresses inward then expands on click.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-holographic-glitch",
    name: "Holographic Glitch",
    description: "Periodic subtle glitch effects with text shifts and RGB channel splits, intensifying on hover.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  // Icon Story Buttons (20 total)
  {
    id: "button-icon-envelope-plane",
    name: "Envelope to Paper Plane",
    description: "Envelope opens, transforms into a paper plane, and flies away with a trail.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-envelope-flap-burst",
    name: "Envelope Flap Burst",
    description: "Envelope bounces, flap pops open, and paper bursts out with a checkmark.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-plane-runway",
    name: "Paper Plane Runway",
    description: "Paper plane rolls along a runway, then takes off in an upward arc.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-inbox-zero-sweep",
    name: "Inbox Zero Sweep",
    description: "A swirling motion sweeps over the inbox, clearing papers and showing a checkmark.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-chat-rocket",
    name: "Chat Bubble Rocket",
    description: "Chat bubble morphs into a rocket shape and blasts upward with particle exhaust.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-typing-blast",
    name: "Typing Dots Blast",
    description: "Typing dots converge into a ball and blast out as a message streak.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-folder-arrow",
    name: "Folder Arrow Launch",
    description: "Folder opens, a file pops up, morphs into an arrow, and rockets upward.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-cloud-reverse",
    name: "Cloud Upload Reverse",
    description: "Raindrops flow upward into the cloud, arrow flips to up, then shows a checkmark.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-heart-confetti",
    name: "Heart Confetti Pop",
    description: "Heart inflates with a bounce, then pops into radial confetti particles.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-star-supernova",
    name: "Star Supernova",
    description: "Star spins rapidly, scales up with glow, then bursts in a supernova effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-music-equalizer",
    name: "Music Equalizer",
    description: "Music note breaks into animated equalizer bars, then compresses back to a note.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-cart-checkout",
    name: "Cart Checkout Arrow",
    description: "Shopping cart shakes, items hop in, then morphs into a checkout arrow that slides right.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-wand-sparkle",
    name: "Magic Wand Sparkle",
    description: "Wand tilts and wiggles, emitting sparkles that swirl and converge into a checkmark.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-portal-morph",
    name: "Portal Morph",
    description: "Circular portal ripples open, icon drops in, and a new icon rises from the portal.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-trash-vacuum",
    name: "Trash Vacuum",
    description: "Trash can lid opens, document gets sucked in with increasing speed, lid slams shut.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-lock-unlock",
    name: "Lock Unlock Slide",
    description: "Padlock shackle opens, lock body slides aside, revealing 'Welcome' text.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-camera-photo",
    name: "Camera Photo Pop",
    description: "Camera recoils with a flash effect, then a photo card slides out and stacks.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-envelope-sequence",
    name: "Envelope Multi Morph",
    description: "Continuous sequence: envelope opens, paper appears, morphs to plane, flies away, shows checkmark.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-flip-card",
    name: "3D Flip Icon Card",
    description: "Card rotates in 3D along Y-axis, revealing a different icon on the back with confirmation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "button-icon-particle-transform",
    name: "Particle Transform",
    description: "Icon dissolves into particles that swirl and converge into a different success icon.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "buttons",
    route: "/playground",
  },
  // GFC Website Animations (4 total)
  {
    id: "gfc-hero-simple-fade",
    name: "GFC Hero – Simple Fade",
    description: "Hero section with fade-in animation for the homepage. Features large heading, subtitle, and CTA button with staggered entrance.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "hero-banner",
    route: "/playground",
  },
  {
    id: "gfc-hero-diagonal-split",
    name: "GFC Hero – Diagonal Split",
    description: "Variant hero with diagonal gold/blue split for Hall Rentals. Features dual-panel layout with sliding diagonal panel and text block.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "hero-banner",
    route: "/playground",
  },
  {
    id: "gfc-announcement-ribbon",
    name: "GFC Announcement Ribbon",
    description: "Thin announcement banner that slides down from the top. Perfect for closures, special events, or important notices.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "banner-status",
    route: "/playground",
  },
  {
    id: "gfc-section-header-gold-underline",
    name: "GFC Section Header – Gold Underline",
    description: "Section heading with animated gold underline. Features optional overline label and spark effect traveling along the underline.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  // GFC Website CTA Buttons (7 total)
  {
    id: "gfc-cta-rent-hall",
    name: "GFC CTA – Rent Hall",
    description: "Website CTA button with gradient and arrow slide for Hall Rentals.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-join",
    name: "GFC CTA – Join the Club",
    description: "CTA button with gold border glow and shake animation on click.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-email",
    name: "GFC CTA – Email Us",
    description: "Email button with envelope lid animation and paper slide effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-donate",
    name: "GFC CTA – Donate",
    description: "Donate button with heartbeat animation and radial glow effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-learn-more",
    name: "GFC CTA – Learn More",
    description: "Learn More button with chevron slide and border pulse animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-book-now",
    name: "GFC CTA – Book Now",
    description: "Book Now button with calendar tilt and page flip effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  {
    id: "gfc-cta-contact",
    name: "GFC CTA – Contact Us",
    description: "Contact button with floating chat bubble and typing dots animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "cta-button",
    route: "/playground",
  },
  // GFC Website Cards & Tiles (6 total)
  {
    id: "gfc-card-membership-stats",
    name: "GFC Card – Membership Stats",
    description: "Floating membership statistics panel with animated number counter and gentle hover effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  {
    id: "gfc-card-hall-feature-strip",
    name: "GFC Strip – Hall Features",
    description: "Horizontal scrolling carousel strip showcasing hall amenities with auto-scroll and hover interactions.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  {
    id: "gfc-card-floorplan-reveal",
    name: "GFC Card – Floorplan Reveal",
    description: "Interactive card that reveals a floorplan overlay on hover with smooth transitions and icon animations.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  {
    id: "gfc-card-photo-mosaic",
    name: "GFC Card – Photo Mosaic",
    description: "Gallery-style photo mosaic card with hover overlay revealing view gallery action.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  {
    id: "gfc-card-event-hover",
    name: "GFC Card – Event",
    description: "Event listing card with hover lift effect, animated date badge, and sliding chevron indicator.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  {
    id: "gfc-card-team-member",
    name: "GFC Card – Team Member",
    description: "Team member profile card with fade-up animation, avatar, and hover accent effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "card-tile",
    route: "/playground",
  },
  // GFC Website Sections & Layout (5 total)
  {
    id: "gfc-section-parallax-hero",
    name: "GFC Section – Parallax Hero",
    description: "Parallax-style hero section demo with background/foreground depth effect for the GFC website.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  {
    id: "gfc-section-history-timeline",
    name: "GFC Section – History Timeline",
    description: "Vertical timeline section showcasing GFC history with scroll-in animations for each milestone.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  {
    id: "gfc-section-rental-steps",
    name: "GFC Section – Rental Steps",
    description: "Three-step rental process section with animated cards and hover interactions.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  {
    id: "gfc-section-wave-divider",
    name: "GFC Divider – Wave",
    description: "Animated wave section divider with SVG path drawing effect and gradient styling.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  {
    id: "gfc-section-sticky-mini-nav",
    name: "GFC Section – Sticky Mini Nav Demo",
    description: "Sticky mini navigation demo with scroll-based active state and smooth section transitions.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "section-layout",
    route: "/playground",
  },
  // GFC Website Banners & Status (4 total) - Phase 5
  // NOTE: For the "New" tab and "Latest only" mode to work correctly,
  // always give newly added presets a strictly later `addedAt` date
  // than previous batches (YYYY-MM-DD). Do NOT reuse the same date
  // for multiple releases if you want older ones to stop being "new".
  {
    id: "gfc-banner-event-countdown",
    name: "GFC Banner – Event Countdown",
    description: "Event countdown banner with animated timer and call-to-action button.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "banner-status",
    route: "/playground",
    addedAt: "2025-11-24",
  },
  {
    id: "gfc-chip-open-rentals",
    name: "GFC Chip – Open for Rentals",
    description: "Status chip indicating the hall is open for bookings with pulsing animation.",
    category: "basic",
    difficulty: 1,
    usageCategory: "gfc-website",
    gfcType: "banner-status",
    route: "/playground",
    addedAt: "2025-11-24",
  },
  {
    id: "gfc-footer-cta-bar",
    name: "GFC Footer – CTA Bar",
    description: "Footer call-to-action bar with animated arrow and gradient background.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "banner-status",
    route: "/playground",
    addedAt: "2025-11-24",
  },
  {
    id: "gfc-strip-contact-info",
    name: "GFC Strip – Contact Info",
    description: "Contact information strip with animated icons and hover effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "banner-status",
    route: "/playground",
    addedAt: "2025-11-24",
  },
  // GFC Website Branding & Impact (5 total) - Phase 6
  {
    id: "gfc-brand-donation-impact-meter",
    name: "GFC Brand – Donation Impact Meter",
    description: "Animated donation progress meter with impact indicators and glowing progress bar.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "branding-impact",
    route: "/playground",
    addedAt: "2025-11-25",
  },
  {
    id: "gfc-brand-crest-highlight",
    name: "GFC Brand – Crest Highlight",
    description: "Animated GFC crest with radial glow and periodic shine sweep effect.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "branding-impact",
    route: "/playground",
    addedAt: "2025-11-25",
  },
  {
    id: "gfc-brand-perfect-for-badges",
    name: "GFC Brand – Perfect For Badges",
    description: "Cluster of animated event type badges with floating animations and hover effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "branding-impact",
    route: "/playground",
    addedAt: "2025-11-25",
  },
  {
    id: "gfc-brand-testimonials-slider",
    name: "GFC Brand – Testimonials Slider",
    description: "Auto-advancing testimonials slider with smooth transitions and navigation dots.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "branding-impact",
    route: "/playground",
    addedAt: "2025-11-25",
  },
  {
    id: "gfc-brand-membership-type-flip-cards",
    name: "GFC Brand – Membership Type Flip Cards",
    description: "3D flip cards showcasing different membership types with hover-triggered animations.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "branding-impact",
    route: "/playground",
    addedAt: "2025-11-25",
  },
  // GFC Website Calendar (6 total) - Phase 7
  {
    id: "gfc-calendar-available-tile",
    name: "GFC Calendar – Available Tile Glow",
    description: "Available date tile with subtle glowing highlight.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  {
    id: "gfc-calendar-booked-tile",
    name: "GFC Calendar – Booked Tile Lock",
    description: "Booked date tile with lock and fade animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  {
    id: "gfc-calendar-pending-tile",
    name: "GFC Calendar – Pending Tile Pulse",
    description: "Pending date tile with pulsating border.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  {
    id: "gfc-calendar-header-slide",
    name: "GFC Calendar – Header Slide",
    description: "Sliding calendar header and weekday labels.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  {
    id: "gfc-calendar-month-switch",
    name: "GFC Calendar – Month Switch",
    description: "Animated month switch between mini calendar views.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  {
    id: "gfc-calendar-range-highlight",
    name: "GFC Calendar – Range Highlight",
    description: "Sweep highlight across multi-day rental range.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-26",
  },
  // GFC Website Calendar Expanded (25 total) - Phase C1
  // Availability Indicators (7)
  {
    id: "gfc-calendar-available-day-pulse",
    name: "GFC Calendar – Available Day Pulse",
    description: "Light green pulse glow around available days with subtle rhythmic bloom.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-available-hover-lift",
    name: "GFC Calendar – Available Hover Lift",
    description: "Available day lifts upward with shadow reveal on hover.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-soft-availability-ripple",
    name: "GFC Calendar – Soft Availability Ripple",
    description: "Gentle radial ripple that signals this day can be booked.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-availability-gradient-sweep",
    name: "GFC Calendar – Availability Gradient Sweep",
    description: "Diagonal green gradient sweep passes through available days.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-faint-checkmark-reveal",
    name: "GFC Calendar – Faint Checkmark Reveal",
    description: "Tiny checkmark appears inside the tile, then fades out.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-morning-evening-color-split",
    name: "GFC Calendar – Morning Evening Color Split",
    description: "Tile splits into top/bottom halves to signal AM/PM availability.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-priority-date-glow",
    name: "GFC Calendar – Priority Date Glow",
    description: "Slight golden glow for days marked as high priority open slots.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  // Booked / Conflict States (7)
  {
    id: "gfc-calendar-booked-day-lock-in",
    name: "GFC Calendar – Booked Day Lock In",
    description: "Tile animates a red lock icon closing, confirming the day is fully booked.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-conflict-shake-red",
    name: "GFC Calendar – Conflict Shake Red",
    description: "Tile performs a small horizontal shake with a red flash on conflict detection.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-full-day-flash-warning",
    name: "GFC Calendar – Full Day Flash Warning",
    description: "Two-event-full days receive an attention-grabbing orange flash animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-blocked-date-stripe",
    name: "GFC Calendar – Blocked Date Stripe",
    description: "Animated diagonal red stripes slide across the blocked day tile.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-gap-rule-violation-pulse",
    name: "GFC Calendar – Gap Rule Violation Pulse",
    description: "Tile pulses in yellow with an alert exclamation to show insufficient gap.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-event-overlap-slide-alert",
    name: "GFC Calendar – Event Overlap Slide Alert",
    description: "Overlapping events animate the two tiles sliding into each other and bouncing apart.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-holiday-seal-stamp",
    name: "GFC Calendar – Holiday Seal Stamp",
    description: "Day receives a stamped emblem animation indicating holiday closure.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  // Event Creation Flow (5)
  {
    id: "gfc-calendar-add-event-slide-up-form",
    name: "GFC Calendar – Add Event Slide Up Form",
    description: "Sliding panel animation from bottom for Add Event modal preview.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-add-event-target-highlight",
    name: "GFC Calendar – Add Event Target Highlight",
    description: "The clicked day expands slightly with a highlight ring before form opens.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-event-created-success-burst",
    name: "GFC Calendar – Event Created Success Burst",
    description: "After event creation, a burst of soft particles animates inside the tile.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-event-denied-shake",
    name: "GFC Calendar – Event Denied Shake",
    description: "A red X appears with a downward bounce and tile shakes slightly.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-event-saved-ribbon",
    name: "GFC Calendar – Event Saved Ribbon",
    description: "A ribbon slides in from top-right of the tile labeled Saved.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  // Admin-Only Visuals (3)
  {
    id: "gfc-calendar-admin-override-glow",
    name: "GFC Calendar – Admin Override Glow",
    description: "Purple glow animation for days where admin override was performed.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-admin-edit-tile-flip",
    name: "GFC Calendar – Admin Edit Tile Flip",
    description: "Tile flips 180° to reveal admin edit mode, then flips back.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-admin-bulk-blocking-sweep",
    name: "GFC Calendar – Admin Bulk Blocking Sweep",
    description: "Multiple tiles animate with a synchronized red sweep indicating bulk block operation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  // Month Navigation & Transitions (3)
  {
    id: "gfc-calendar-month-slide-left",
    name: "GFC Calendar – Month Slide Left",
    description: "Smooth leftward slide when navigating to next month.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-month-slide-right",
    name: "GFC Calendar – Month Slide Right",
    description: "Smooth rightward slide when navigating to previous month.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  {
    id: "gfc-calendar-month-fade-reveal",
    name: "GFC Calendar – Month Fade Reveal",
    description: "Old month fades out, new month fades in with a soft scaling gradient.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-27",
  },
  // UI Animations (9 total)
  {
    id: "password-strength-meter",
    name: "Password Strength Meter",
    description: "Interactive password strength indicator with animated meter bar and visibility toggle.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "forms-auth",
    route: "/playground",
  },
  {
    id: "glass-login-switcher",
    name: "Glass Login Switcher",
    description: "Glassmorphism-style authentication panel with smooth sign in/sign up toggle animation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "forms-auth",
    route: "/playground",
  },
  {
    id: "magic-play-button",
    name: "Magic Play Button",
    description: "Floating 3D play button with orbiting glow blobs and gradient background effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "buttons",
    route: "/playground",
  },
  {
    id: "liquid-distortion-text",
    name: "Liquid Distortion Text",
    description: "Hero text with liquid distortion effect using animated transforms and SVG filters.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "text-fx",
    route: "/playground",
  },
  {
    id: "neon-border-card",
    name: "Neon Border Card",
    description: "Card with continuously animated neon gradient border using conic gradient rotation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "card-tile",
    route: "/playground",
  },
  {
    id: "product-configurator-card",
    name: "Product Configurator Card",
    description: "Interactive product customization card with animated option selection and visual updates.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "card-tile",
    route: "/playground",
  },
  {
    id: "hover-info-reveal-card",
    name: "Hover Info Reveal Card",
    description: "Card with 3D flip animation revealing additional information on hover.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "card-tile",
    route: "/playground",
  },
  {
    id: "dashboard-metrics-tiles",
    name: "Dashboard Metrics Tiles",
    description: "Grid of metric tiles with staggered entrance animations and hover lift effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "dashboards-metrics",
    route: "/playground",
  },
  {
    id: "image-uploader-gallery",
    name: "Image Uploader Gallery",
    description: "Drag-and-drop image uploader with animated gallery preview and thumbnail management.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "media-galleries",
    route: "/playground",
  },
  // Phase C2 - 25 New Calendar Animations
  {
    id: "calendar-page-flip",
    name: "Calendar Page Flip",
    description: "Calendar page flips with 3D rotation effect when switching months.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-date-pulse",
    name: "Calendar Date Pulse",
    description: "Dates pulse with a rhythmic glow animation to draw attention.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-day-glow",
    name: "Calendar Day Glow",
    description: "Individual day tiles glow with a continuous pulsing effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-week-slide",
    name: "Calendar Week Slide",
    description: "Week view slides horizontally to show different weeks.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-pop-in-event",
    name: "Calendar Pop In Event",
    description: "Event indicators pop in with a spring animation when events are added.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-booked-stamp",
    name: "Calendar Booked Stamp",
    description: "Booked dates receive a stamp-like animation with lock icon.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-available-fade",
    name: "Calendar Available Fade",
    description: "Available dates fade in and out with a gentle pulsing effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-drag-add-event",
    name: "Calendar Drag Add Event",
    description: "Interactive drag-and-drop interface for adding events to calendar dates.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-bounce-day-marker",
    name: "Calendar Bounce Day Marker",
    description: "Day marker bounces up and down to indicate the current or selected date.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-swipe-month",
    name: "Calendar Swipe Month",
    description: "Smooth swipe transition between months with fade and slide effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-peel-back-reveal",
    name: "Calendar Peel Back Reveal",
    description: "3D peel-back effect reveals additional information or status.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-highlight-range",
    name: "Calendar Highlight Range",
    description: "Multi-day range selection with animated highlight across selected dates.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-dot-pop",
    name: "Calendar Dot Pop",
    description: "Event indicator dots pop in with a spring animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-event-ribbon",
    name: "Calendar Event Ribbon",
    description: "Event ribbon appears with a diagonal fold animation on dates with events.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-month-carousel",
    name: "Calendar Month Carousel",
    description: "Month selector carousel with smooth transitions between months.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-fog-unavailable",
    name: "Calendar Fog Unavailable",
    description: "Unavailable dates are dimmed with a foggy overlay effect.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-flash-available",
    name: "Calendar Flash Available",
    description: "Available dates flash with a bright highlight to draw attention.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-event-ping",
    name: "Calendar Event Ping",
    description: "Event dates ping with a ripple effect to indicate activity.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-event-drop-in",
    name: "Calendar Event Drop In",
    description: "Events drop into place with a gravity-based animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-availability-checker",
    name: "Calendar Availability Checker",
    description: "Availability status is checked with an animated checkmark reveal.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-tap-to-add",
    name: "Calendar Tap To Add",
    description: "Interactive tap animation for adding events with visual feedback.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-heat-map-glow",
    name: "Calendar Heat Map Glow",
    description: "Heat map visualization with varying glow intensities based on activity.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-soft-wave-transition",
    name: "Calendar Soft Wave Transition",
    description: "Soft wave animation transitions between calendar states.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-event-flag-rise",
    name: "Calendar Event Flag Rise",
    description: "Event flags rise up from dates to indicate important events.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  {
    id: "calendar-booked-lock-in",
    name: "Calendar Booked Lock In",
    description: "Booked dates lock in with a rotating lock icon animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar",
    route: "/playground",
    addedAt: "2025-11-28",
  },
  // Phase C3 - 10 Event Creation Animations
  {
    id: "calendar-create-event-pop",
    name: "Calendar Create Event Pop",
    description: "Event creation pop animation with spring effect when clicking a date.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-drag-to-create-slot",
    name: "Calendar Drag To Create Slot",
    description: "Interactive drag-and-drop interface for creating event slots on calendar dates.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-event-expand-form",
    name: "Calendar Event Expand Form",
    description: "Event form expands from a date tile with smooth animation transitions.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-day-press-popup",
    name: "Calendar Day Press Popup",
    description: "Popup menu appears when pressing a calendar day with event creation options.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-slide-in-event-creator",
    name: "Calendar Slide In Event Creator",
    description: "Event creator panel slides in from the bottom with smooth spring animation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-tap-add-marker",
    name: "Calendar Tap Add Marker",
    description: "Tap interaction adds a visual marker to indicate event creation on a date.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-event-grow-highlight",
    name: "Calendar Event Grow Highlight",
    description: "Date tile grows and highlights when selected for event creation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-drop-event-into-day",
    name: "Calendar Drop Event Into Day",
    description: "Event drops into a calendar day with gravity-based animation and confirmation.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-select-window-pulse",
    name: "Calendar Select Window Pulse",
    description: "Time selection window pulses to indicate active selection mode.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "calendar-event-bubble-rise",
    name: "Calendar Event Bubble Rise",
    description: "Event creation bubble rises from a date with smooth upward animation.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "calendar-event-creation",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  // Flags & Patriotic
  {
    id: "gfc-american-flag-wave",
    name: "American Flag – Realistic Wave",
    description: "A realistic American flag gently waving in the wind on a dark background.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "flags-patriotic",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "gfc-american-flag-webgl",
    name: "American Flag – WebGL Wave",
    description: "A realistic 3D waving American flag rendered with WebGL.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "gfc-website",
    gfcType: "flags-patriotic",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "american-flag-advanced",
    name: "American Flag – Advanced Wave",
    description: "Professional slice-based 3D wave with modern lighting.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "portuguese-flag-realistic-wave",
    name: "Portuguese Flag – Realistic Wave",
    description: "A realistic Portuguese flag waving with the same advanced cloth effect.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  // Flags & Nations Category - Core Dual-Flag Animations
  {
    id: "flags_dual_ribbon_weave",
    name: "Dual-Flag Ribbon Weave",
    description: "Both flags start as horizontal ribbons, weave over/under each other, then snap into full flags side-by-side with gentle swaying.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_star_to_shield_morph",
    name: "Star-to-Shield Morph",
    description: "US flag stars detach and cluster, morphing into Portuguese coat-of-arms shield while background transitions from stripes to green/red.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_wind_wave_sync",
    name: "Wind-Wave Sync",
    description: "Two flags side-by-side with synchronized wind motion simulating cloth waves, moving in perfect sync as if on the same gust of wind.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_split_screen_merge",
    name: "Split-Screen Merge",
    description: "Left half US flag, right half Portuguese flag, they slide together to merge in center, then optionally swap sides.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_particle_burst_reveal",
    name: "Particle Burst Flag Reveal",
    description: "Particles burst from center in flag colors, then fall back to assemble into two rectangles which resolve into the two flags with gentle glow.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_heart_dual_flag",
    name: "Heart-Shape Dual Flag",
    description: "Ribbons of US and PT colors spiral inward to form a heart outline, then the interior fills with a blended pattern (left half US, right half PT) with subtle pulsing.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_crossed_flagpoles_3d",
    name: "3D Crossing Flagpoles",
    description: "Two slim poles rotate in from offscreen and cross in X formation, flags unfurl from top with a short delay and then settle into a light waving loop.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_flip_card_transition",
    name: "Flip-Card Flag Transition",
    description: "US flag card flips around its vertical axis, mid-flip swaps to Portuguese flag, continues flipping back and forth, then both flags appear side-by-side.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_split_stripes_transform",
    name: "Split Stripes Transform",
    description: "US flag stripes peel downward one by one, recolor and reposition to form the red/green halves of a Portuguese-like flag layout, with union morphing into Portuguese emblem.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_firework_ignite_reveal",
    name: "Fireworks Ignite Reveal",
    description: "Dark background with fireworks on left (US: red/white/blue) and right (PT: red/green/gold), each explosion briefly reveals portions of the corresponding flag behind it.",
    category: "advanced",
    difficulty: 3,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  // Flags & Nations Category - Holiday Variants
  {
    id: "flags_holiday_new_year",
    name: "New Year's Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with bright confetti, gold sparkles, and festive New Year's celebration effects.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_us_independence",
    name: "US Independence Day Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with fireworks in red/white/blue, more US focus with subtle Portuguese presence for July 4th celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_pt_dia_de_portugal",
    name: "Portugal Day Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with fireworks in red/green/gold, more Portuguese focus with subtle US presence for June 10th celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_thanksgiving",
    name: "Thanksgiving Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with warm oranges/browns, leaf/confetti motif behind both flags for Thanksgiving celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_memorial_day",
    name: "Memorial Day Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with subdued, respectful tones, gentle glow, and minimal particles for Memorial Day observance.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_christmas",
    name: "Christmas Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with snow-like particles, red/green accents, and both flags with soft glow for Christmas celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_easter",
    name: "Easter Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with pastels, soft bokeh, and flags floating in a calm spring-like backdrop for Easter celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
  {
    id: "flags_holiday_labor_day",
    name: "Labor Day Dual Flags",
    description: "Holiday-themed dual-flag animation (American & Portuguese) with patriotic confetti, yet more subdued than July 4th, for US Labor Day celebration.",
    category: "intermediate",
    difficulty: 2,
    usageCategory: "flags",
    route: "/playground",
    addedAt: "2025-11-29",
  },
];

// Helper function to get animation by ID
export function getAnimationMetaById(id: string): AnimationMeta | undefined {
  return animations.find((anim) => anim.id === id);
}

// Helper function to get animations by category
export function getAnimationsByCategory(
  category: string
): AnimationMeta[] {
  return animations.filter((anim) => anim.category === category);
}

// Helper function to get default route for an animation
export function getAnimationRoute(id: string): string {
  const meta = getAnimationMetaById(id);
  if (meta?.route) {
    return meta.route;
  }
  // Default route pattern
  return `/animations/${id}`;
}

