// <auto-generated />
using System;
using GFC.BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GFC.BlazorServer.Data.Migrations
{
    [DbContext(typeof(GfcDbContext))]
    [Migration("20251222203249_AddDiagnosticsAndCameraCredentials")]
    partial class AddDiagnosticsAndCameraCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.CardReaderProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DigitsOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastSampleParsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSampleRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("PrefixToTrim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SuffixToTrim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CardReaderProfiles", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerBehaviorOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValidSwipeGapSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId")
                        .IsUnique();

                    b.ToTable("ControllerBehaviorOptions", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerCommandInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOperation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWriteOperation")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProtocolInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ControllerCommandInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Door Control",
                            DisplayName = "Open Door",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "OpenDoor",
                            LongDescription = "Sends the Agent OpenDoor command which issues the Mengqi type 32/code 1 packet with optional duration override.",
                            Phase = "Phase 1",
                            ProtocolInfo = "Agent POST /{sn}/door/{doorNo}/open",
                            RiskLevel = 1,
                            ShortDescription = "Momentarily energize a door relay for a door or elevator output."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Timekeeping",
                            DisplayName = "Sync Controller Time",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncTime",
                            LongDescription = "Uses the AdjustTime command (type 32/code 48) via the Agent to ensure logs timestamps stay accurate.",
                            Phase = "Phase 1",
                            ProtocolInfo = "Agent POST /{sn}/sync-time",
                            RiskLevel = 0,
                            ShortDescription = "Align the controller RTC with the server clock."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Privileges",
                            DisplayName = "Add or Update Card",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "AddOrUpdateCard",
                            LongDescription = "Wraps the Mengqi privilege packet (type 36/code 62) through the Agent bulk/individual privilege APIs.",
                            Phase = "Phase 3A",
                            ProtocolInfo = "Agent POST /{sn}/cards",
                            RiskLevel = 1,
                            ShortDescription = "Apply a single card privilege row to the controller."
                        },
                        new
                        {
                            Id = 4,
                            Category = "Privileges",
                            DisplayName = "Delete Card",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "DeleteCard",
                            LongDescription = "Marks the privilege row as deleted via the Agent DELETE /cards/{cardNo} endpoint.",
                            Phase = "Phase 3A",
                            ProtocolInfo = "Agent DELETE /{sn}/cards/{cardNo}",
                            RiskLevel = 1,
                            ShortDescription = "Remove a single card slot from the controller."
                        },
                        new
                        {
                            Id = 5,
                            Category = "Privileges",
                            DisplayName = "Clear All Cards",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "ClearAllCards",
                            LongDescription = "Triggers the dangerous type 36/code 64 command through the Agent ClearAllCards API.",
                            Phase = "Phase 3A",
                            ProtocolInfo = "Agent POST /{sn}/cards/clear-all",
                            RiskLevel = 3,
                            ShortDescription = "Erase the entire privilege table."
                        },
                        new
                        {
                            Id = 6,
                            Category = "Privileges",
                            DisplayName = "Bulk Upload Cards",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "BulkUploadCards",
                            LongDescription = "Uses the Agent bulk upload endpoint which internally sequences the WGPacket privilege writes.",
                            Phase = "Phase 3A",
                            ProtocolInfo = "Agent POST /{sn}/cards/bulk-upload",
                            RiskLevel = 2,
                            ShortDescription = "Stream a batch of privilege rows to the controller."
                        },
                        new
                        {
                            Id = 7,
                            Category = "Monitoring",
                            DisplayName = "Read Events",
                            Enabled = true,
                            IsReadOperation = true,
                            IsWriteOperation = false,
                            Key = "ReadEvents",
                            LongDescription = "Calls Agent GET /events which wraps GetLastRecordIndex + GetSingleSwipeRecord + confirm index.",
                            Phase = "Phase 2",
                            ProtocolInfo = "Agent GET /{sn}/events?lastIndex=x",
                            RiskLevel = 0,
                            ShortDescription = "Fetch swipe/event records since the last index."
                        },
                        new
                        {
                            Id = 8,
                            Category = "Monitoring",
                            DisplayName = "Read Run/Status Block",
                            Enabled = true,
                            IsReadOperation = true,
                            IsWriteOperation = false,
                            Key = "ReadRunStatus",
                            LongDescription = "Uses Agent GET /run-status which relays the Mengqi run info command (type 32/code 32).",
                            Phase = "Phase 2",
                            ProtocolInfo = "Agent GET /{sn}/run-status",
                            RiskLevel = 0,
                            ShortDescription = "Poll live door, relay, and alarm states."
                        },
                        new
                        {
                            Id = 9,
                            Category = "Configuration",
                            DisplayName = "Sync Door Configuration",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncDoorConfig",
                            LongDescription = "Uses Agent POST /door-config/sync which maps to extended config flash writes.",
                            Phase = "Phase 3B",
                            ProtocolInfo = "Agent POST /{sn}/door-config/sync",
                            RiskLevel = 2,
                            ShortDescription = "Write door timing/mode settings."
                        },
                        new
                        {
                            Id = 10,
                            Category = "Schedules",
                            DisplayName = "Sync Time Profiles",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncTimeProfiles",
                            LongDescription = "Wraps the Agent POST /time-schedules/sync endpoint that fills the holiday/time zone blocks.",
                            Phase = "Phase 3C",
                            ProtocolInfo = "Agent POST /{sn}/time-schedules/sync",
                            RiskLevel = 2,
                            ShortDescription = "Write controller time zones / schedules."
                        },
                        new
                        {
                            Id = 11,
                            Category = "Schedules",
                            DisplayName = "Sync Holidays",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncHolidays",
                            LongDescription = "Part of the same FLASH region as time profiles; triggered through the schedule sync API.",
                            Phase = "Phase 3C",
                            ProtocolInfo = "Included in POST /{sn}/time-schedules/sync",
                            RiskLevel = 2,
                            ShortDescription = "Update the holiday block used by privilege filtering."
                        },
                        new
                        {
                            Id = 12,
                            Category = "Schedules",
                            DisplayName = "Sync Auto Open Tasks",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncAutoOpen",
                            LongDescription = "Uses the Agent POST /auto-open/sync endpoint to replace the task table.",
                            Phase = "Phase 2F",
                            ProtocolInfo = "Agent POST /{sn}/auto-open/sync",
                            RiskLevel = 2,
                            ShortDescription = "Write automatic door unlock/lock tasks."
                        },
                        new
                        {
                            Id = 13,
                            Category = "Configuration",
                            DisplayName = "Sync Advanced Door Modes",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncAdvancedDoorModes",
                            LongDescription = "Maps to Agent POST /advanced-door-modes/sync which writes the extended FRAM structures.",
                            Phase = "Phase 2F",
                            ProtocolInfo = "Agent POST /{sn}/advanced-door-modes/sync",
                            RiskLevel = 2,
                            ShortDescription = "Write extended per-door options (double lock, first card, etc.)."
                        },
                        new
                        {
                            Id = 14,
                            Category = "Maintenance",
                            DisplayName = "Reboot Controller",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "RebootController",
                            LongDescription = "Agent POST /reboot triggers the Mengqi special command (type 32/code 254).",
                            Phase = "Phase 5",
                            ProtocolInfo = "Agent POST /{sn}/reboot",
                            RiskLevel = 3,
                            ShortDescription = "Soft reboot the panel."
                        },
                        new
                        {
                            Id = 15,
                            Category = "Configuration",
                            DisplayName = "Sync Network Config",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncNetworkConfig",
                            LongDescription = "Changes the controller's network configuration. Incorrect settings may cause loss of connectivity.",
                            Phase = "Phase 4F",
                            ProtocolInfo = "Agent POST /{sn}/network-config",
                            RiskLevel = 3,
                            ShortDescription = "Update controller IP address, subnet mask, gateway, and port."
                        },
                        new
                        {
                            Id = 16,
                            Category = "Configuration",
                            DisplayName = "Sync Allowed PC IP",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncAllowedPc",
                            LongDescription = "Sets which PC IP address is allowed to communicate with the controller. Incorrect settings may block legitimate access.",
                            Phase = "Phase 4F",
                            ProtocolInfo = "Agent POST /{sn}/allowed-pc",
                            RiskLevel = 3,
                            ShortDescription = "Update the allowed PC IP address whitelist."
                        },
                        new
                        {
                            Id = 17,
                            Category = "Configuration",
                            DisplayName = "Sync Controller Password",
                            Enabled = true,
                            IsReadOperation = false,
                            IsWriteOperation = true,
                            Key = "SyncControllerPassword",
                            LongDescription = "Updates the password required for controller communication. If forgotten, controller may become inaccessible.",
                            Phase = "Phase 4F",
                            ProtocolInfo = "Agent POST /{sn}/allowed-pc",
                            RiskLevel = 3,
                            ShortDescription = "Change the controller's communication password."
                        });
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerCommandLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ControllerCommandLogs", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Controllers", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoorId")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsByButton")
                        .HasColumnType("bit");

                    b.Property<bool>("IsByCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("bit");

                    b.Property<string>("RawData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RawIndex")
                        .HasColumnType("int");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("ControllerId", "RawIndex")
                        .HasDatabaseName("IX_ControllerEvents_Controller_RawIndex");

                    b.ToTable("ControllerEvents", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerLastIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<long>("LastRecordIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId")
                        .IsUnique();

                    b.ToTable("ControllerLastIndexes");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerNetworkConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedPcIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CommPasswordMasked")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DhcpEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Gateway")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("LastReadUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId")
                        .IsUnique();

                    b.ToTable("ControllerNetworkConfigs", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerTimeProfileLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<int>("ControllerProfileIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("TimeProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeProfileId");

                    b.HasIndex("ControllerId", "ControllerProfileIndex")
                        .IsUnique();

                    b.HasIndex("ControllerId", "TimeProfileId")
                        .IsUnique();

                    b.ToTable("ControllerTimeProfileLinks", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<int>("DoorIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId", "DoorIndex")
                        .IsUnique();

                    b.ToTable("Doors", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorAutoOpenSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ControllerProfileIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DoorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("TimeProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId")
                        .IsUnique();

                    b.HasIndex("TimeProfileId");

                    b.ToTable("DoorAutoOpenSchedules", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorBehaviorOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoorAsSwitchEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("DoorId")
                        .HasColumnType("int");

                    b.Property<bool>("FirstCardOpenEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Invalid3CardsWarnEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("OpenTooLongWarnEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId")
                        .IsUnique();

                    b.ToTable("DoorBehaviorOptions", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoorId")
                        .HasColumnType("int");

                    b.Property<int>("LockDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("OpenTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId")
                        .IsUnique();

                    b.ToTable("DoorConfigs", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DuesPayment", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId", "Year");

                    b.ToTable("DuesPayments", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Holidays", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.KeyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("Date");

                    b.HasIndex("MemberId");

                    b.ToTable("KeyHistory", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.MemberDoorAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DoorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastSyncResult")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("TimeProfileId");

                    b.HasIndex("MemberId", "DoorId", "CardNumber");

                    b.ToTable("MemberDoorAccess", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.NPQueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("QueuePosition");

                    b.ToTable("NPQueueEntries", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReceiptFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestItemId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestItemId");

                    b.HasIndex("UploadedByMemberId");

                    b.ToTable("ReceiptFiles", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ReimbursementCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "BJ's"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Supplies"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Misc"
                        });
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByMemberId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangeUtc");

                    b.HasIndex("ChangedByMemberId");

                    b.HasIndex("RequestId");

                    b.ToTable("ReimbursementChangeLogs", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequestId");

                    b.ToTable("ReimbursementItems", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EditedFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaidByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("date");

                    b.Property<int>("RequestorMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestDate");

                    b.HasIndex("RequestorMemberId");

                    b.HasIndex("Status");

                    b.ToTable("ReimbursementRequests", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NotificationRecipients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceiptRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReimbursementSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReceiptRequired = false
                        });
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScannerControllerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TaskEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<int?>("Door")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.ToTable("TaskEntries", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TimeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TimeProfiles", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TimeProfileInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TimeProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeProfileId", "DayOfWeek", "Order");

                    b.ToTable("TimeProfileIntervals", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.UserNotificationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ControllerEventNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ControllerEventNotifySMS")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DuesPaymentNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("DuesPaymentNotifySMS")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LotterySalesNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("LotterySalesNotifySMS")
                        .HasColumnType("bit");

                    b.Property<bool>("MemberSignupNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("MemberSignupNotifySMS")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationReminderDismissed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NotificationReminderDismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReimbursementNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ReimbursementNotifySMS")
                        .HasColumnType("bit");

                    b.Property<bool>("SystemAlertNotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("SystemAlertNotifySMS")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserNotificationPreferences");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.Waiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "Year");

                    b.ToTable("Waivers", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PasswordChangeRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RtspUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cameras", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.CameraAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("UserId");

                    b.ToTable("CameraAuditLogs", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.CameraEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("CameraEvents", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.CameraPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("UserId");

                    b.ToTable("CameraPermissions", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.Diagnostics.AlertThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MetricType")
                        .HasColumnType("int");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AlertThresholds");
                });

            modelBuilder.Entity("GFC.Core.Models.Diagnostics.DiagnosticAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AlertThresholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlertThresholdId");

                    b.ToTable("DiagnosticAlerts");
                });

            modelBuilder.Entity("GFC.Core.Models.Diagnostics.PerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("int");

                    b.Property<int>("ActiveThreads")
                        .HasColumnType("int");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("float");

                    b.Property<int>("Gen0Collections")
                        .HasColumnType("int");

                    b.Property<int>("Gen1Collections")
                        .HasColumnType("int");

                    b.Property<int>("Gen2Collections")
                        .HasColumnType("int");

                    b.Property<double>("MemoryUsageGb")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsagePercentage")
                        .HasColumnType("float");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PerformanceSnapshots");
                });

            modelBuilder.Entity("GFC.Core.Models.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("Recordings", (string)null);
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerBehaviorOptions", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerCommandLog", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerEvent", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany("Events")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GFC.BlazorServer.Data.Entities.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Controller");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerLastIndex", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithOne("LastIndex")
                        .HasForeignKey("GFC.BlazorServer.Data.Entities.ControllerLastIndex", "ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerNetworkConfig", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerTimeProfileLink", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFC.BlazorServer.Data.Entities.TimeProfile", "TimeProfile")
                        .WithMany()
                        .HasForeignKey("TimeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("TimeProfile");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.Door", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany("Doors")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorAutoOpenSchedule", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFC.BlazorServer.Data.Entities.TimeProfile", "TimeProfile")
                        .WithMany()
                        .HasForeignKey("TimeProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Door");

                    b.Navigation("TimeProfile");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorBehaviorOptions", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.DoorConfig", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.Door", "Door")
                        .WithOne()
                        .HasForeignKey("GFC.BlazorServer.Data.Entities.DoorConfig", "DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.MemberDoorAccess", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFC.BlazorServer.Data.Entities.TimeProfile", "TimeProfile")
                        .WithMany()
                        .HasForeignKey("TimeProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Door");

                    b.Navigation("TimeProfile");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReceiptFile", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ReimbursementItem", "RequestItem")
                        .WithMany("ReceiptFiles")
                        .HasForeignKey("RequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestItem");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementChangeLog", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ReimbursementRequest", "Request")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementItem", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ReimbursementCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GFC.BlazorServer.Data.Entities.ReimbursementRequest", "Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TaskEntry", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.ControllerDevice", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TimeProfileInterval", b =>
                {
                    b.HasOne("GFC.BlazorServer.Data.Entities.TimeProfile", "TimeProfile")
                        .WithMany("Intervals")
                        .HasForeignKey("TimeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeProfile");
                });

            modelBuilder.Entity("GFC.Core.Models.CameraAuditLog", b =>
                {
                    b.HasOne("GFC.Core.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFC.Core.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GFC.Core.Models.CameraEvent", b =>
                {
                    b.HasOne("GFC.Core.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("GFC.Core.Models.CameraPermission", b =>
                {
                    b.HasOne("GFC.Core.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFC.Core.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GFC.Core.Models.Diagnostics.DiagnosticAlert", b =>
                {
                    b.HasOne("GFC.Core.Models.Diagnostics.AlertThreshold", "AlertThreshold")
                        .WithMany()
                        .HasForeignKey("AlertThresholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertThreshold");
                });

            modelBuilder.Entity("GFC.Core.Models.Recording", b =>
                {
                    b.HasOne("GFC.Core.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ControllerDevice", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("Events");

                    b.Navigation("LastIndex");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementItem", b =>
                {
                    b.Navigation("ReceiptFiles");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.ReimbursementRequest", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GFC.BlazorServer.Data.Entities.TimeProfile", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
