// <auto-generated />
using System;
using GFC.BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GFC.BlazorServer.Data.Migrations
{
    [DbContext(typeof(GfcDbContext))]
    [Migration("20251223054722_AddStudioPersistence")]
    partial class AddStudioPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GFC.Core.Models.StudioPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudioPages", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.StudioSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimationSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageIndex")
                        .HasColumnType("int");

                    b.Property<int>("StudioPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudioPageId");

                    b.ToTable("StudioSections", (string)null);
                });

            modelBuilder.Entity("GFC.Core.Models.StudioSection", b =>
                {
                    b.HasOne("GFC.Core.Models.StudioPage", "StudioPage")
                        .WithMany("Sections")
                        .HasForeignKey("StudioPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudioPage");
                });

            modelBuilder.Entity("GFC.Core.Models.StudioPage", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
