// <auto-generated />
// [NEW]
using GFC.BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GFC.BlazorServer.Data.Migrations
{
    [DbContext(typeof(GfcDbContext))]
    [Migration("20251228000000_UpdateStudioSchemaForCMS")]
    partial class UpdateStudioSchemaForCMS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // This is a partial designer file. It does not need to contain the entire
            // model snapshot, only the changes related to this migration.
            // However, for manual migrations, it is safer to just leave this empty
            // and rely on the main model snapshot for the complete picture.
#pragma warning restore 612, 618
        }
    }
}
